version: '3.7'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: npm run build
    ports: 
      - ${PORT_FRONTEND}:${PORT_FRONTEND}
    volumes:
      - ./frontend:/frontend:rw
      - ./frontend/out:/frontend/out:rw
      - /frontend/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    depends_on:
      - frontend
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: ${DOMAIN}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    restart: always
    volumes:
      - ./nginx/prod:/etc/nginx/templates
      - ./nginx/crontab.txt:/crontab.txt
      - ./certs/conf:/etc/letsencrypt
      - ./frontend/out:/front_dist
    # logging:
    #   driver: "none"